In [22]:
import numpy as np
print("libraries imported successfully")

#libraries were imprted succesfully
from scipy.linalg import fractional_matrix_power


P_0 = np.matrix([0, 0, 0, -1, -1, 1]).T
print(" Initial label vector P0:\n", P_0)

# Similarity matrix S
S = np.array([[0, 1, 0, 0, 1, 1],
              [1, 0, 1, 1, 0, 0],
              [0, 1, 0, 1, 0, 0],
              [0, 1, 1, 0, 0, 0],
              [1, 0, 0, 0, 0, 0],
              [1, 0, 0, 0, 0, 0]])

# Normalize similarity matrix 
# Similarity matrix S for this graph (with all edges = 1) 
def sim_norm(S):
    D_ = np.diag(np.sum(S, axis=1))
    D_neg_half = fractional_matrix_power(D_, -0.5)
    S_norm = np.matmul(np.matmul(D_neg_half, S), D_neg_half)
    return np.round(S_norm, 3)

S_norm = sim_norm(S)

print("\nSimilarity matrix S:\n", S)
print("\nNormalized similarity matrix S_norm:\n", S_norm)

# Label spreading - 1 iteration, α = 0.8
alpha = 0.8
P_1 = (1 - alpha) * P_0 + alpha * np.matmul(S_norm, P_0)
[l0, l1, l2] = np.concatenate(P_1[:3])

print("\nLabel spreading - 1 iteration, α = 0.8:")
print("P_1 =\n", np.round(P_1, 3))
print("\nl0 = {}, l1 = {}, l2 = {}".format(l0, l1, l2))

# Label spreading - 2 iterations, α = 0.8
P_2 = (1 - alpha) * P_1 + alpha * np.matmul(S_norm, P_1)
[l0, l1, l2] = np.concatenate(P_2[:3])

print("\n3. Label spreading - 2 iterations, α = 0.8:")
print("P_2 =\n", np.round(P_2, 3))
print("\nl0 = {}, l1 = {}, l2 = {}".format(l0, l1, l2))

# Infinite label spreading, α = 0.8
I = np.identity(S_norm.shape[0])
I_aS_neg1 = fractional_matrix_power(I - alpha * S_norm, -1.0)
P_inf = np.round((1 - alpha) * np.matmul(I_aS_neg1, P_0), 3)
[l0, l1, l2] = np.concatenate(P_inf[:3])

print("\n4. Infinite label spreading, α = 0.8:")
print("P_inf =\n", P_inf)
print("\nl0 = {}, l1 = {}, l2 = {}".format(l0, l1, l2))

# Energy minimization
D = np.diag(np.sum(S, axis=1))
L = D - S
L_uu = L[:3, :3]
L_ul = L[:3, 3:]
Y_l = P_0[3:]
F_u = np.round(np.matmul(-fractional_matrix_power(L_uu, -1.0), np.matmul(L_ul, Y_l)), 3)
[l0, l1, l2] = np.round(F_u, 3).tolist()[:3]

print("\n5. Energy minimization:")
print("F_u =\n", F_u)
print("\nl0 = {}, l1 = {}, l2 = {}".format(l0, l1, l2))


libraries imported successfully
 Initial label vector P0:
 [[ 0]
 [ 0]
 [ 0]
 [-1]
 [-1]
 [ 1]]

Similarity matrix S:
 [[0 1 0 0 1 1]
 [1 0 1 1 0 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]

Normalized similarity matrix S_norm:
 [[0.    0.333 0.    0.    0.577 0.577]
 [0.333 0.    0.408 0.408 0.    0.   ]
 [0.    0.408 0.    0.5   0.    0.   ]
 [0.    0.408 0.5   0.    0.    0.   ]
 [0.577 0.    0.    0.    0.    0.   ]
 [0.577 0.    0.    0.    0.    0.   ]]

Label spreading - 1 iteration, α = 0.8:
P_1 =
 [[ 0.   ]
 [-0.326]
 [-0.4  ]
 [-0.2  ]
 [-0.2  ]
 [ 0.2  ]]

l0 = [[0.]], l1 = [[-0.3264]], l2 = [[-0.4]]

3. Label spreading - 2 iterations, α = 0.8:
P_2 =
 [[-0.087]
 [-0.261]
 [-0.267]
 [-0.307]
 [-0.04 ]
 [ 0.04 ]]

l0 = [[-0.08695296]], l1 = [[-0.26112]], l2 = [[-0.26653696]]

4. Infinite label spreading, α = 0.8:
P_inf =
 [[-0.097]
 [-0.209]
 [-0.209]
 [-0.352]
 [-0.245]
 [ 0.155]]

l0 = -0.097, l1 = -0.209, l2 = -0.209

5. Energy minimization:
F_u =
 [[-0.