In [5]:
# 1. 5 Points. Find a nonnegative factorization of the matrix

import numpy as np

from sklearn.decomposition import NMF

# Given matrix A

A = np.array([[4,6,5],[1,2,3],[7,10,7],[6,8,4],[6,10,11]])

# Define the rank (number of components)

K = 2

# Perform NMF

model = NMF(n_components=K, init='nndsvd', max_iter=1000)

B = model.fit_transform(A)

C = model.components_

# The resulting W and H matrices are nonnegative factors of A

print("B matrix:")

print(B)

print("C matrix:")

print(C)

B matrix:
[[1.52149232 0.80021142]
 [0.38039818 0.80023512]
 [2.66258645 0.80018772]
 [2.28216784 0.        ]
 [2.28228869 2.40068167]]
C matrix:
[[2.62901151 3.50546977 1.75274086]
 [0.         0.83288027 2.91573551]]


In [6]:
import numpy as np
from sklearn.decomposition import NMF

# Given matrix A
A = np.array([[4, 6, 5], [1, 2, 3], [7, 10, 7], [6, 8, 4], [6, 10, 11]])

# Define the rank (number of components)
rank = 2

# Randomly initialize B and C
B_init = np.random.rand(A.shape[0], rank)
C_init = np.random.rand(rank, A.shape[1])

# Perform NMF
model = NMF(n_components=rank, init='custom')
B = model.fit_transform(A, W=B_init, H=C_init)
C = model.components_

# Approximation of A
A_approx = np.dot(B, C)

print("approximate nonnegative factorization of A:")
print(A_approx)


approximate nonnegative factorization of A:
[[ 3.99996681  5.99998381  5.00009392]
 [ 1.00149964  2.0013326   2.99857599]
 [ 7.00001646 10.00000803  7.00008771]
 [ 6.00009928  8.00004844  3.99998758]
 [ 5.99980116  9.99990298 11.00029418]]
